import 'package:flutter/material.dart';

final Map<String, IconData> weatherCodesIcons = {
  'Clear sky': Icons.wb_sunny,
  'Mainly clear': Icons.wb_sunny_outlined,
  'Partly cloudy': Icons.wb_cloudy_outlined,
  'Overcast': Icons.cloud,
  'Fog': Icons.cloud,
  'Depositing rime fog': Icons.cloud,
  'Drizzle: Light': Icons.water_drop,
  'Drizzle: Moderate': Icons.water_drop,
  'Drizzle: Dense': Icons.water_drop,
  'Freezing Drizzle: Light': Icons.water_drop,
  'Freezing Drizzle: Dense': Icons.water_drop,
  'Rain: Slight': Icons.water_drop,
  'Rain: Moderate': Icons.water_drop,
  'Rain: Heavy': Icons.water_drop,
  'Freezing Rain: Light': Icons.cloudy_snowing,
  'Freezing Rain: Heavy': Icons.cloudy_snowing,
  'Snow fall: Slight': Icons.snowing,
  'Snow fall: Moderate': Icons.snowing,
  'Snow fall: Heavy': Icons.snowing,
  'Snow grains': Icons.snowing,
  'Rain showers: Slight': Icons.cloudy_snowing,
  'Rain showers: Moderate': Icons.cloudy_snowing,
  'Rain showers: Violent': Icons.cloudy_snowing,
  'Snow showers slight': Icons.snowing,
  'Snow showers heavy': Icons.snowing,
  'Thunderstorm: Slight or moderate': Icons.thunderstorm,
  'Thunderstorm with slight hail': Icons.thunderstorm,
  'Thunderstorm with heavy hail': Icons.thunderstorm,
};